.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. beta_qt test_beta_qt
clean: FORCE
	$(MAKE) -C .. beta_qt_clean test_beta_qt_clean
check: FORCE
	$(MAKE) -C .. test_beta_qt_check
beta-qt beta-qt.exe: FORCE
	 $(MAKE) -C .. beta_qt
